config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'
  get "home/about" => "homes#about", as: "about"
  devise_for :users
  resources :books
  resources :users, only: [:show,:index,:edit,:update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title,presence: true
  validates :body,presence: true, length: {maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  validates :name, uniqueness: true, length: {in: 2..20}
  validates :introduction, {length: {maximum:50}}

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit,:update]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: 'You have created book successfully.'
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
    def book_params
      params.require(:book).permit(:title, :body)
    end

    def correct_user
      @book = Book.find(params[:id])
      @user = @book.user
      redirect_to(books_path) unless @user == current_user
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit,:update]

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: 'You have updated user successfully.'
    else
      render :edit
    end
  end


  private
    def user_params
      params.require(:user).permit(:name,:profile_image,:introduction)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(user_path(current_user.id)) unless @user == current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
          <h1>User info</h1>
            <p><%= image_tag user.get_profile_image(100,100) %></p>
            <table class="User_info">
              <tbody>
                <tr></tr>
                <tr>
                  <th>name</th>
                  <th><%= user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= user.introduction %></th>
                </tr>
              </tbody>
            </table>
          <div class="row">
            <%= link_to edit_user_path(user.id), class: "btn btn-outline-dark btn-block" do %>
              <i class="fas fa-user-cog"></i>
            <% end %>
          </div>
          <h1>New book</h1>
            <%= form_with model: book, url: '/books', method: :post do |f| %>
              <h4>Title</h4>
                <%= f.text_field :title %>
              <h4>Opinion</h4>
                <%= f.text_area :body %>
                <%= f.submit 'Create Book' %>
            <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
 <div class="row">
     <div class="mx-auto col-sm-12 col-md-8 col-lg-5">
         <h1>Editing Book</h1>
         <% if @book.errors.any? %>
          <%= @book.errors.count %>error prohibited this obj from being saved:
            <ul>
              <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
              <% end %>
            </ul>
        <% end %>

            <%= form_with model: @book do |f| %>
             <div class="Booktitle">
              <p>Title</p>
                <%= f.text_field :title %>
            </div>
            <div class="Bookbody">
              <p>Opinion</p>
                <%= f.text_area :body %>
            </div>
            <div>
              <%= f.submit "Update Book" %>
            </div>
            <% end %>
        <%= link_to "Show", book_path(@book.id) %>
        <%= link_to "Back", books_path %>
    </div>
 </div>
</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
   </ul>
<% end %>

<div class="container">
  <div class="row">
    <!--部分テンプレここから-->
    <%= render 'list', book: @book, user: @user %>
        <!--部分テンプレここまで-->
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
          <table class="mybooks">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
            <%  @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.id) do %>
                    <%= image_tag book.user.get_profile_image(80,80) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
      </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
 <div class="row">
     <!--部分テンプレート-->
     <%= render 'list', book: @new_book, user: @user %>

    <div class="col-md-8 offset-md-1">
        <h1>Book detail</h1>
        <table>
            <tbody>
                <tr>
                    <td>
                        <%= link_to user_path(@user.id) do %>
                            <%= image_tag @book.user.get_profile_image(100,100) %>
                            <%= @book.user.name %>
                        <% end %>
                    </td>
                    <td><%= @book.title %></td>
                    <td><%= @book.body %></td>
                <% if @book.user == current_user %>
                    <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
                    <td><%= link_to "Destroy", book_path(@book.id), method: :delete %></td>
                <% end %>
                </tr>
            </tbody>
        </table>
    </div>
 </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>
      <p>
        In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </p>
      <p>you can share and exchange your opinions , inpressions , and emotions</p>
      <p>about various books!</p>
    <div class="mx-auto">
      <div class="row">
        <a href= "new_user_session_path" class="mx-auto btn btn-info btn-block btn-sm">Log in</a>
      </div>
      <div class="row">
        <a href="new_user_registration_path" class="mx-auto btn btn-success btn-block btn-sm">Sign up</a>
      </div>
    </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/1bfa5a428d.js" crossorigin="anonymous"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <!--Bookersは全てtopページに飛ぶ-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

          <a class="nav-brand p-2" href="/">Bookers</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-cotrols="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navgation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <!--自分の一覧-->
                <li>
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
              <!--userの一覧-->
                <li>
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users"></i>Users
                  <% end %>
                </li>
              <!--投稿一覧-->
                <li>
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                   <i class="fas fa-book-open"></i>Books
                  <% end %>
                </li>
              <!--ログアウト-->
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i>Log out
                  <% end %>
                </li>

              <% else %>
              <!--topページ-->
                <li>
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
              <!--aboutページ-->
                <li>
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link"></i>About
                  <% end %>
                </li>
                <!--新規登録ページ-->
                <li>
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus"></i>Sign up
                  <% end %>
                </li>
                <!--ログインページ-->
                <li>
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt"></i>Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
        </div>
        </div>
      </nav>
    </header>

    <main>
      <%= flash[:notice] %>
      <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
             <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
    <div class="row"></div>
        <div class="mx-auto col-sm-12 col-md-8 col-lg-5">
            <h1>User info</h1>
            <% if @user.errors.any? %>
                <%= @user.errors.count %>error prohibited this obj from being saved:
                <ul>
                    <% @user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                </ul>
            <% end %>

            <%= form_with model: @user do |f| %>
            <div>
                <p>Name</p>
                  <%= f.text_field :name %>
            </div>
            <div>
                <p>Image</p>
                <%= f.file_field :profile_image,  accept: "image/*" %>
            </div>
            <div>
                <p>Introduction</p>
                <%= f.text_area :introduction %>
            </div>
            <div class="btn btn-sm">
                <%= f.submit "Update User" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <!--部分テンプレ-->
    <%= render 'books/list', book: @book, user: @user %>

    <div class="col-md-8 offset-md-1">
      <h1>Users</h1>
      <table>
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
        </thead>
      <% @users.each do |user| %>
        <tbody>
          <tr>
            <td><%= image_tag user.get_profile_image(80,80) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        </tbody>
      <% end %>
      </table>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <!--部分テンプレ-->
    <%= render 'books/list', book: @book, user: @user %>
    <!--ここまで-->
    <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
          <table class="mybooks">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
            <%  @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(@user.id) do %>
                    <%= image_tag book.user.get_profile_image(100,100) %>
                  <% end %>
                </td>
                <td>
                  <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                  <% end %>
                </td>
                <td><%= book.body %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
      </div>
  </div>
</div>